import type { Config } from 'tailwindcss';
import { psephoTailwindPreset } from '@psepho/tokens/tailwind';

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/*/src/**/*.{js,ts,jsx,tsx}',
  ],
  presets: [psephoTailwindPreset],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#484554',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#797586',
        'outline-variant': '#c9c4d7',
        'surface-tint': '#6042d6',
        primary: '#451ebb',
        'on-primary': '#ffffff',
        'primary-container': '#5d3fd3',
        'on-primary-container': '#d8ceff',
        'inverse-primary': '#cabeff',
        secondary: '#00696e',
        'on-secondary': '#ffffff',
        'secondary-container': '#00f4fe',
        'on-secondary-container': '#006c71',
        tertiary: '#8c002e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b80040',
        'on-tertiary-container': '#ffc6cb',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e6deff',
        'primary-fixed-dim': '#cabeff',
        'on-primary-fixed': '#1c0062',
        'on-primary-fixed-variant': '#4723be',
        'secondary-fixed': '#63f7ff',
        'secondary-fixed-dim': '#00dce5',
        'on-secondary-fixed': '#002021',
        'on-secondary-fixed-variant': '#004f53',
        'tertiary-fixed': '#ffd9dc',
        'tertiary-fixed-dim': '#ffb2ba',
        'on-tertiary-fixed': '#400011',
        'on-tertiary-fixed-variant': '#910030',
        background: '#faf8ff',
        'on-background': '#131b2e',
        'surface-variant': '#dae2fd',
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-padding-mobile': '20px',
        'container-padding-desktop': '40px',
        'card-gap': '24px',
        'section-margin': '64px',
      },
      fontFamily: {
        display: ["'Bricolage Grotesque'", 'sans-serif'],
        'display-lg': ["'Bricolage Grotesque'", 'sans-serif'],
        'display-lg-mobile': ["'Bricolage Grotesque'", 'sans-serif'],
        'headline-lg': ["'Bricolage Grotesque'", 'sans-serif'],
        'headline-md': ["'Bricolage Grotesque'", 'sans-serif'],
        body: ["'Inter'", 'sans-serif'],
        'body-lg': ["'Inter'", 'sans-serif'],
        'body-md': ["'Inter'", 'sans-serif'],
        'label-bold': ["'Inter'", 'sans-serif'],
        caption: ["'Inter'", 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
