import { Poll } from './types';

export const initialPolls: Poll[] = [
  // 1. Featured Poll
  {
    id: 'poll-featured-remote',
    slug: 'remote-vs-office',
    question: 'Work remotely or from an office?',
    category: 'Work & Tech',
    kind: 'featured',
    badge: { label: 'Trending Debate', type: 'trending' },
    status: 'open',
    closesIn: '2 days',
    totalVotes: 184219,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    options: [
      {
        id: 'opt-remote',
        label: 'Remote',
        subtitle: 'Focus and flexibility',
        icon: 'home_work',
        votes: 114216,
        percentage: 62,
      },
      {
        id: 'opt-office',
        label: 'Office',
        subtitle: 'Collaboration and culture',
        icon: 'corporate_fare',
        votes: 70003,
        percentage: 38,
      },
    ],
    regionalBreakdown: {
      South: { region: 'South', percentage: 76, votes: 68000, density: 'high' },
      West: { region: 'West', percentage: 71, votes: 45000, density: 'medium' },
      North: { region: 'North', percentage: 68, votes: 41000, density: 'medium' },
      East: { region: 'East', percentage: 63, votes: 19219, density: 'low' },
      Central: { region: 'Central', percentage: 65, votes: 11000, density: 'low' },
    },
    demographicBreakdown: [
      { cohort: '18-24', supportPct: 78, nationalPct: 62, divergence: 16 },
      { cohort: '25-34', supportPct: 71, nationalPct: 62, divergence: 9 },
      { cohort: '35-49', supportPct: 56, nationalPct: 62, divergence: -6 },
      { cohort: '50+', supportPct: 43, nationalPct: 62, divergence: -19 },
    ],
    discoveryNote:
      'South India leans most toward remote work, showing a 13% variance from the East.',
  },

  // 2. Divided 1
  {
    id: 'poll-divided-ai',
    slug: 'ai-creative-jobs',
    question: 'AI in creative jobs: Tool or Threat?',
    category: 'Work & Tech',
    kind: 'divided',
    badge: { label: 'High tension', type: 'tension' },
    status: 'open',
    closesIn: '3 days',
    totalVotes: 12450,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    options: [
      {
        id: 'opt-tool',
        label: 'Tool',
        subtitle: 'Productivity and inspiration',
        icon: 'smart_toy',
        votes: 6349,
        percentage: 51,
      },
      {
        id: 'opt-threat',
        label: 'Threat',
        subtitle: 'Displacement and originality erosion',
        icon: 'warning',
        votes: 6101,
        percentage: 49,
      },
    ],
    regionalBreakdown: {
      South: { region: 'South', percentage: 55, votes: 4200, density: 'high' },
      West: { region: 'West', percentage: 52, votes: 3000, density: 'medium' },
      North: { region: 'North', percentage: 48, votes: 2900, density: 'medium' },
      East: { region: 'East', percentage: 46, votes: 1550, density: 'low' },
      Central: { region: 'Central', percentage: 50, votes: 800, density: 'low' },
    },
    demographicBreakdown: [
      { cohort: '18-24', supportPct: 64, nationalPct: 51, divergence: 13 },
      { cohort: '25-34', supportPct: 53, nationalPct: 51, divergence: 2 },
      { cohort: '35-49', supportPct: 45, nationalPct: 51, divergence: -6 },
      { cohort: '50+', supportPct: 38, nationalPct: 51, divergence: -13 },
    ],
    discoveryNote: 'Generation gap is acute: 18-24 views AI overwhelmingly as a multiplier tool.',
  },

  // 3. Divided 2
  {
    id: 'poll-divided-ubi',
    slug: 'universal-basic-income',
    question: 'Universal Basic Income',
    category: 'Economy & Future',
    kind: 'divided',
    badge: { label: 'Active Debate', type: 'tension' },
    status: 'open',
    closesIn: '4 days',
    totalVotes: 45120,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    options: [
      {
        id: 'opt-ubi-for',
        label: 'For',
        subtitle: 'Security floor and economic freedom',
        icon: 'savings',
        votes: 21658,
        percentage: 48,
      },
      {
        id: 'opt-ubi-against',
        label: 'Against',
        subtitle: 'Fiscal strain and work disincentives',
        icon: 'account_balance',
        votes: 23462,
        percentage: 52,
      },
    ],
    regionalBreakdown: {
      South: { region: 'South', percentage: 52, votes: 15000, density: 'high' },
      West: { region: 'West', percentage: 46, votes: 11200, density: 'medium' },
      North: { region: 'North', percentage: 49, votes: 10300, density: 'medium' },
      East: { region: 'East', percentage: 44, votes: 5820, density: 'low' },
      Central: { region: 'Central', percentage: 47, votes: 2800, density: 'low' },
    },
    demographicBreakdown: [
      { cohort: '18-24', supportPct: 61, nationalPct: 48, divergence: 13 },
      { cohort: '25-34', supportPct: 50, nationalPct: 48, divergence: 2 },
      { cohort: '35-49', supportPct: 42, nationalPct: 48, divergence: -6 },
      { cohort: '50+', supportPct: 35, nationalPct: 48, divergence: -13 },
    ],
    discoveryNote: 'Urban metro youth show 61% support, whereas self-employed lean 58% against.',
  },

  // 4. Divided 3
  {
    id: 'poll-divided-rto',
    slug: 'mandatory-rto',
    question: 'Mandatory return to office',
    category: 'Work & Tech',
    kind: 'divided',
    badge: { label: 'Deadlock', type: 'tension' },
    status: 'open',
    closesIn: '5 days',
    totalVotes: 89340,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    options: [
      {
        id: 'opt-rto-support',
        label: 'Support',
        subtitle: 'Real camaraderie and mentoring',
        icon: 'domain',
        votes: 44670,
        percentage: 50,
      },
      {
        id: 'opt-rto-oppose',
        label: 'Oppose',
        subtitle: 'Loss of autonomy and commute penalty',
        icon: 'commute',
        votes: 44670,
        percentage: 50,
      },
    ],
    regionalBreakdown: {
      South: { region: 'South', percentage: 42, votes: 32000, density: 'high' },
      West: { region: 'West', percentage: 53, votes: 23500, density: 'medium' },
      North: { region: 'North', percentage: 55, votes: 18800, density: 'medium' },
      East: { region: 'East', percentage: 54, votes: 9540, density: 'low' },
      Central: { region: 'Central', percentage: 51, votes: 5500, density: 'low' },
    },
    demographicBreakdown: [
      { cohort: '18-24', supportPct: 34, nationalPct: 50, divergence: -16 },
      { cohort: '25-34', supportPct: 42, nationalPct: 50, divergence: -8 },
      { cohort: '35-49', supportPct: 61, nationalPct: 50, divergence: 11 },
      { cohort: '50+', supportPct: 69, nationalPct: 50, divergence: 19 },
    ],
    discoveryNote: 'Exact deadlock nationally; managerial cohorts lead support while junior staff oppose.',
  },

  // 5. Surprising 1
  {
    id: 'poll-surprising-4day',
    slug: '4-day-workweek',
    question: '4-day workweek',
    category: 'Work & Tech',
    kind: 'surprising',
    badge: { label: 'Most Surprising', type: 'surprising' },
    status: 'open',
    closesIn: '6 days',
    totalVotes: 54200,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    options: [
      {
        id: 'opt-4day-yes',
        label: 'Yes',
        subtitle: 'Condensed hours, equivalent output',
        icon: 'calendar_month',
        votes: 44444,
        percentage: 82,
      },
      {
        id: 'opt-4day-no',
        label: 'No',
        subtitle: 'Impractical for service operations',
        icon: 'schedule',
        votes: 9756,
        percentage: 18,
      },
    ],
    regionalBreakdown: {
      South: { region: 'South', percentage: 86, votes: 20600, density: 'high' },
      West: { region: 'West', percentage: 81, votes: 14100, density: 'medium' },
      North: { region: 'North', percentage: 79, votes: 10300, density: 'medium' },
      East: { region: 'East', percentage: 78, votes: 5900, density: 'low' },
      Central: { region: 'Central', percentage: 80, votes: 3300, density: 'low' },
    },
    demographicBreakdown: [
      { cohort: '18-24', supportPct: 91, nationalPct: 82, divergence: 9 },
      { cohort: '25-34', supportPct: 88, nationalPct: 82, divergence: 6 },
      { cohort: '35-49', supportPct: 76, nationalPct: 82, divergence: -6 },
      { cohort: '50+', supportPct: 64, nationalPct: 82, divergence: -18 },
    ],
    discoveryNote:
      '91% support among 18-24 demographic, shifting the average heavily.',
  },

  // 6. Surprising 2
  {
    id: 'poll-surprising-social',
    slug: 'social-media-age-limits',
    question: 'Social media age limits',
    category: 'Society & Governance',
    kind: 'surprising',
    badge: { label: 'Most Surprising', type: 'surprising' },
    status: 'open',
    closesIn: '1 day',
    totalVotes: 31800,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    options: [
      {
        id: 'opt-social-agree',
        label: 'Agree',
        subtitle: 'Strict verification under 16',
        icon: 'child_care',
        votes: 21624,
        percentage: 68,
      },
      {
        id: 'opt-social-disagree',
        label: 'Disagree',
        subtitle: 'Parental purview, not platform gating',
        icon: 'lock_open',
        votes: 10176,
        percentage: 32,
      },
    ],
    regionalBreakdown: {
      South: { region: 'South', percentage: 70, votes: 11300, density: 'high' },
      West: { region: 'West', percentage: 69, votes: 8400, density: 'medium' },
      North: { region: 'North', percentage: 66, votes: 6600, density: 'medium' },
      East: { region: 'East', percentage: 65, votes: 3600, density: 'low' },
      Central: { region: 'Central', percentage: 67, votes: 1900, density: 'low' },
    },
    demographicBreakdown: [
      { cohort: '18-24', supportPct: 61, nationalPct: 68, divergence: -7 },
      { cohort: '25-34', supportPct: 67, nationalPct: 68, divergence: -1 },
      { cohort: '35-49', supportPct: 74, nationalPct: 68, divergence: 6 },
      { cohort: '50+', supportPct: 79, nationalPct: 68, divergence: 11 },
    ],
    discoveryNote:
      'Surprisingly high agreement across all age groups, not just parents.',
  },
];
