// AUTO-GENERATED by tools/geo-build — do not edit by hand.
// Run `cd tools/geo-build && npm install && npm run build` to regenerate.
//
// Boundaries: DataMeet India community Census 2011 district maps (MIT), relabelled
// to the present-day States & UTs, and udit-001/india-maps-data for current
// districts. India is drawn with its external boundary as claimed by India.
// World coastlines: Natural Earth 1:50m via world-atlas (public domain).

import type { GeoMap } from './../types';

const map: GeoMap = {
  id: "in-ch",
  name: "Chandigarh",
  width: 1943,
  height: 2016,
  shapes: [
  {
    id: "ch-chandigarh",
    name: "Chandigarh",
    code: "CH",
    label: [1013,1101],
    bbox: [8,8,1935,2008],
    d: "M1648,1783L1391,2008L1370,2005L1150,1879L971,1962L802,1710L467,1608L358,1128L8,823L77,545L530,406L905,8L1053,250L1053,389L1122,362L1464,240L1497,290L1506,300L1355,475L1488,667L1645,502L1796,644L1799,637L1711,876L1929,1015L1935,1068L1926,1250L1627,1680Z",
  },
  ],
};

export default map;
