// AUTO-GENERATED by tools/geo-build — do not edit by hand.
// Run `cd tools/geo-build && npm install && npm run build` to regenerate.
//
// Boundaries: DataMeet India community Census 2011 district maps (MIT), relabelled
// to the present-day States & UTs, and udit-001/india-maps-data for current
// districts. India is drawn with its external boundary as claimed by India.
// World coastlines: Natural Earth 1:50m via world-atlas (public domain).

import type { GeoMap } from './../types';

const map: GeoMap = {
  id: "in-dh",
  name: "Dadra & Nagar Haveli and Daman & Diu",
  width: 2016,
  height: 647,
  shapes: [
  {
    id: "dh-dadra-and-nagar-haveli",
    name: "Dadra and Nagar Haveli",
    code: "DH",
    label: [1884,437],
    bbox: [1748,357,2008,639],
    d: "M1790,407L1782,398L1789,382L1805,390L1806,392L1800,409L1797,414ZM1790,495L1786,472L1759,456L1748,438L1764,416L1798,439L1806,421L1830,420L1828,400L1836,403L1836,417L1851,419L1858,389L1888,391L1905,357L1917,378L1909,409L1951,396L1964,403L1965,422L1957,430L1946,424L1944,436L1906,467L1906,478L1882,474L1873,481L1864,503L1873,508L1877,540L1885,543L1890,527L1921,546L1924,532L1943,523L1937,503L1939,498L1956,504L1966,495L1974,509L1986,505L2008,515L2000,533L1993,536L1984,535L1982,568L2002,575L2002,607L1983,614L1986,639L1964,635L1939,606L1918,617L1910,603L1877,595L1869,595L1867,626L1859,624L1823,583L1832,562L1820,555L1815,578L1801,580L1792,569L1803,521L1789,517ZM1811,488L1823,488L1827,474L1804,472L1804,476L1800,479L1804,483L1804,488Z",
  },
  {
    id: "dh-daman",
    name: "Daman",
    code: "DH",
    label: [1695,324],
    bbox: [1669,259,1737,350],
    d: "M1725,264L1733,280L1715,279L1700,303L1736,306L1737,310L1722,323L1733,340L1699,345L1682,345L1676,349L1669,350L1682,272L1698,259Z",
  },
  {
    id: "dh-diu",
    name: "Diu",
    code: "DH",
    label: [78,28],
    bbox: [8,8,120,47],
    d: "M46,8L61,17L80,13L97,26L113,9L120,13L103,26L111,35L94,45L53,36L28,47L8,39L16,23L42,17Z",
  },
  ],
};

export default map;
