// AUTO-GENERATED by tools/geo-build — do not edit by hand.
// Run `cd tools/geo-build && npm install && npm run build` to regenerate.
//
// Boundaries: DataMeet India community Census 2011 district maps (MIT), relabelled
// to the present-day States & UTs, and udit-001/india-maps-data for current
// districts. India is drawn with its external boundary as claimed by India.
// World coastlines: Natural Earth 1:50m via world-atlas (public domain).

import type { GeoMap } from '../types';

/**
 * District maps are code-split: a State's districts are only downloaded when a
 * viewer actually drills into that State.
 */
export const DISTRICT_MAP_LOADERS: Record<string, () => Promise<GeoMap>> = {
  "in-an": () => import('./an').then((m) => m.default),
  "in-ap": () => import('./ap').then((m) => m.default),
  "in-ar": () => import('./ar').then((m) => m.default),
  "in-as": () => import('./as').then((m) => m.default),
  "in-br": () => import('./br').then((m) => m.default),
  "in-ch": () => import('./ch').then((m) => m.default),
  "in-cg": () => import('./cg').then((m) => m.default),
  "in-dh": () => import('./dh').then((m) => m.default),
  "in-dl": () => import('./dl').then((m) => m.default),
  "in-ga": () => import('./ga').then((m) => m.default),
  "in-gj": () => import('./gj').then((m) => m.default),
  "in-hr": () => import('./hr').then((m) => m.default),
  "in-hp": () => import('./hp').then((m) => m.default),
  "in-jk": () => import('./jk').then((m) => m.default),
  "in-jh": () => import('./jh').then((m) => m.default),
  "in-ka": () => import('./ka').then((m) => m.default),
  "in-kl": () => import('./kl').then((m) => m.default),
  "in-la": () => import('./la').then((m) => m.default),
  "in-ld": () => import('./ld').then((m) => m.default),
  "in-mp": () => import('./mp').then((m) => m.default),
  "in-mh": () => import('./mh').then((m) => m.default),
  "in-mn": () => import('./mn').then((m) => m.default),
  "in-ml": () => import('./ml').then((m) => m.default),
  "in-mz": () => import('./mz').then((m) => m.default),
  "in-nl": () => import('./nl').then((m) => m.default),
  "in-od": () => import('./od').then((m) => m.default),
  "in-py": () => import('./py').then((m) => m.default),
  "in-pb": () => import('./pb').then((m) => m.default),
  "in-rj": () => import('./rj').then((m) => m.default),
  "in-sk": () => import('./sk').then((m) => m.default),
  "in-tn": () => import('./tn').then((m) => m.default),
  "in-tg": () => import('./tg').then((m) => m.default),
  "in-tr": () => import('./tr').then((m) => m.default),
  "in-up": () => import('./up').then((m) => m.default),
  "in-uk": () => import('./uk').then((m) => m.default),
  "in-wb": () => import('./wb').then((m) => m.default),
};
