// AUTO-GENERATED by tools/geo-build — do not edit by hand.
// Run `cd tools/geo-build && npm install && npm run build` to regenerate.
//
// Boundaries: DataMeet India community Census 2011 district maps (MIT), relabelled
// to the present-day States & UTs, and udit-001/india-maps-data for current
// districts. India is drawn with its external boundary as claimed by India.
// World coastlines: Natural Earth 1:50m via world-atlas (public domain).

import type { GeoMap } from './../types';

const map: GeoMap = {
  id: "in-ld",
  name: "Lakshadweep",
  width: 2007,
  height: 2016,
  shapes: [
  {
    id: "ld-lakshadweep",
    name: "Lakshadweep",
    code: "LD",
    label: [800,1803],
    bbox: [8,8,1999,2008],
    d: "M1202,1698L827,2008L8,1631L990,1626L1999,8Z",
  },
  ],
};

export default map;
